export const GRAPHQL_URL = <string>process.env.NEXT_APP_GRAPHQL_URL
export const GRAPHQL_TOKEN = <string>process.env.NEXT_APP_GRAPHQL_TOKEN
export const PAGE_ARTICLES_COUNT = +process.env.NEXT_PUBLIC_PAGE_ARTICLES_COUNT!
export const CATEGORIES_SIDEBAR_COUNT = +process.env.NEXT_PUBLIC_CATEGORIES_SIDEBAR_COUNT!