
export const LightTheme = {
        '--color-primary': '#0E9CD9',
        '--color-onPrimary': '#ffffff',
        '--color-bg': '#ffffff',
        '--color-onBg': '#222222',
        '--color-error': '#ff3232',
        '--color-success': '#2dd02a',
        '--color-input-bg': '#f5f5f5',
        '--color-input-placeholderColor': '#3f3f3f',
        '--color-input-color': '#222222',
        '--color-text-display': '#111111',
        '--color-text-title': '#1e1e1e',
        '--color-text-body': '#3e3e3e',
        '--color-text-caution': '#3e3e3ed9',
        '--card-shadow': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 0 9px -2px rgb(0 0 0 / 0.1)',
        '--card-shadowHover': '2px 5px 25px -5px rgb(0 0 0 / 10%), 6px 8px 10px -6px rgb(0 0 0 / 10%)',
        '--card-bg': '#ffffff',
        '--color-icon-bg': '#11111120',
        '--color-gray-100': '#99999925',
    }
    export const DarkTheme = {
        '--color-primary': '#0E9CD9',
        '--color-onPrimary': '#ffffff',
        '--color-bg': '#181818',
        '--color-onBg': '#fafafa',
        '--color-error': '#ff3232',
        '--color-success': '#2dd02a',
        '--color-input-bg': '#3f3f3f',
        '--color-input-placeholderColor': '#e0e0e0',
        '--color-input-color': '#fafafa',
        '--color-text-display': '#ffffff',
        '--color-text-title': '#fafafa',
        '--color-text-body': '#e9e9e9',
        '--color-text-caution': '#e9e9e9d9',
        '--card-shadow': 'none',
        '--card-shadowHover': 'none',
        '--card-bg': '#333333',
        '--color-icon-bg': '#333333',
        '--color-gray-100': '#ffffff25',
}